# coding: utf-8

"""
    Dell APEX Cloud Platform for Microsoft Azure REST API

    Dell APEX Cloud Platform REST API provides a programmatic interface for performing administrative tasks on Dell APEX Cloud Platform for Microsoft Azure. The data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 1.0.000
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StorageNetworkSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'network_adapter_name': 'str',
        'vlan_id': 'int',
        'netmask': 'str',
        'storage_adapter_ip_info': 'list[StorageNetworkSpecStorageAdapterIpInfo]'
    }

    attribute_map = {
        'name': 'name',
        'network_adapter_name': 'network_adapter_name',
        'vlan_id': 'vlan_id',
        'netmask': 'netmask',
        'storage_adapter_ip_info': 'storage_adapter_ip_info'
    }

    def __init__(self, name=None, network_adapter_name=None, vlan_id=None, netmask=None, storage_adapter_ip_info=None):  # noqa: E501
        """StorageNetworkSpec - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._network_adapter_name = None
        self._vlan_id = None
        self._netmask = None
        self._storage_adapter_ip_info = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if network_adapter_name is not None:
            self.network_adapter_name = network_adapter_name
        if vlan_id is not None:
            self.vlan_id = vlan_id
        if netmask is not None:
            self.netmask = netmask
        if storage_adapter_ip_info is not None:
            self.storage_adapter_ip_info = storage_adapter_ip_info

    @property
    def name(self):
        """Gets the name of this StorageNetworkSpec.  # noqa: E501

        Name of the storage network.  # noqa: E501

        :return: The name of this StorageNetworkSpec.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this StorageNetworkSpec.

        Name of the storage network.  # noqa: E501

        :param name: The name of this StorageNetworkSpec.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def network_adapter_name(self):
        """Gets the network_adapter_name of this StorageNetworkSpec.  # noqa: E501

        Name of the network adapter for storage network.  # noqa: E501

        :return: The network_adapter_name of this StorageNetworkSpec.  # noqa: E501
        :rtype: str
        """
        return self._network_adapter_name

    @network_adapter_name.setter
    def network_adapter_name(self, network_adapter_name):
        """Sets the network_adapter_name of this StorageNetworkSpec.

        Name of the network adapter for storage network.  # noqa: E501

        :param network_adapter_name: The network_adapter_name of this StorageNetworkSpec.  # noqa: E501
        :type: str
        """

        self._network_adapter_name = network_adapter_name

    @property
    def vlan_id(self):
        """Gets the vlan_id of this StorageNetworkSpec.  # noqa: E501

        Specifies the VLAN ID for the VLAN storage network. This setting is applied to the network interfaces that route the storage and VM migration traffic. The supported values are 1 to 4094.  # noqa: E501

        :return: The vlan_id of this StorageNetworkSpec.  # noqa: E501
        :rtype: int
        """
        return self._vlan_id

    @vlan_id.setter
    def vlan_id(self, vlan_id):
        """Sets the vlan_id of this StorageNetworkSpec.

        Specifies the VLAN ID for the VLAN storage network. This setting is applied to the network interfaces that route the storage and VM migration traffic. The supported values are 1 to 4094.  # noqa: E501

        :param vlan_id: The vlan_id of this StorageNetworkSpec.  # noqa: E501
        :type: int
        """

        self._vlan_id = vlan_id

    @property
    def netmask(self):
        """Gets the netmask of this StorageNetworkSpec.  # noqa: E501

        Specifies the netmask for the storage network.  # noqa: E501

        :return: The netmask of this StorageNetworkSpec.  # noqa: E501
        :rtype: str
        """
        return self._netmask

    @netmask.setter
    def netmask(self, netmask):
        """Sets the netmask of this StorageNetworkSpec.

        Specifies the netmask for the storage network.  # noqa: E501

        :param netmask: The netmask of this StorageNetworkSpec.  # noqa: E501
        :type: str
        """

        self._netmask = netmask

    @property
    def storage_adapter_ip_info(self):
        """Gets the storage_adapter_ip_info of this StorageNetworkSpec.  # noqa: E501

        IP address configuration of the storage network for each host.  # noqa: E501

        :return: The storage_adapter_ip_info of this StorageNetworkSpec.  # noqa: E501
        :rtype: list[StorageNetworkSpecStorageAdapterIpInfo]
        """
        return self._storage_adapter_ip_info

    @storage_adapter_ip_info.setter
    def storage_adapter_ip_info(self, storage_adapter_ip_info):
        """Sets the storage_adapter_ip_info of this StorageNetworkSpec.

        IP address configuration of the storage network for each host.  # noqa: E501

        :param storage_adapter_ip_info: The storage_adapter_ip_info of this StorageNetworkSpec.  # noqa: E501
        :type: list[StorageNetworkSpecStorageAdapterIpInfo]
        """

        self._storage_adapter_ip_info = storage_adapter_ip_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StorageNetworkSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StorageNetworkSpec):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
